# Lektion 6 - Introduktion till deep learning-ramverk
## Assignment: Tensors and a tiny neural network

Instructions:
1. Choose PyTorch or Keras
2. Keep the model small and run quickly
3. Explain what each block does
"""



## Task 1: Tensor operations
TODO: Create a tensor with shape (2, 3)

In [7]:
import torch 


device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"

A = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print(A)
print("A shape:", A.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
A shape: torch.Size([2, 3])


TODO: Reshape to (3, 2)


In [9]:
B = A.reshape(3,2)
print(B)
print("\n B shape:", B.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

 B shape: torch.Size([3, 2])


TODO: Demonstrate broadcasting with another tensor


In [11]:
C = torch.tensor([10.0, 20.0]) #shape (2,)
D = B + C
print("\nC shape:", C.shape)
print("D = B + C (broadcasted):")
print(D)


C shape: torch.Size([2])
D = B + C (broadcasted):
tensor([[11., 22.],
        [13., 24.],
        [15., 26.]])



## Task 2: Build a tiny neural network
TODO: Use MNIST or iris (flattened)

In [12]:
import torch 
import torch.nn as nn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1) Data: Load + split + scale
iris = load_iris()


TODO: Build a model with:
- 1 hidden layer (ReLU)
- output layer (softmax or sigmoid)


## Task 3: Compare APIs
TODO: Write 4-6 comment lines on:
- where PyTorch feels lower level
- where Keras feels higher level